repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
        args:
          - --markdown-linebreak-ext=md
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  #      - id: no-commit-to-branch
  #        args:
  #          - --branch=master

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.43.0
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
        args:
          - "--args=--anchor=false"
      - id: terraform_tflint
        stages: [push]
        args:
          #          - '--args=--deep'   # requires credentials
          - "--args=--enable-rule=terraform_deprecated_index"
          - "--args=--enable-rule=terraform_unused_declarations"
          - "--args=--enable-rule=terraform_comment_syntax"
          - "--args=--enable-rule=terraform_documented_outputs"
          - "--args=--enable-rule=terraform_documented_variables"
          - "--args=--enable-rule=terraform_typed_variables"
          - "--args=--enable-rule=terraform_naming_convention"
          - "--args=--enable-rule=terraform_required_version"
          - "--args=--enable-rule=terraform_required_providers"
#          - '--args=--enable-rule=terraform_standard_module_structure'
